spring:
  application:
    name: shipping-service
  cloud:
    stream:
      function:
        definition: process
      kafka:
        streams:
          binder:
            configuration:
              application:
                id: shipping-service
              schema:
                registry:
                  url: http://localhost:8081
              value:
                subject:
                  name:
                    strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
          bindings:
            process-in-0:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            process-in-1:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
            process-out-0:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      bindings:
        process-in-0:
          destination: customer
        process-in-1:
          destination: order
        process-out-0:
          destination: order

server:
  port: 8086

logging:
  level:
    org.springframework.kafka.config: debug
